### ISSUE TITLE
[CombatTracker] Conditions - Multiple Set

### ISSUE THREAD

**Issue by teak421** [RobinKuiper/Roll20APIScripts#11]
No token was selected when I clicked on Frightened inside of CT.  The attached screenshot shows 5 non-selected tokens getting frightened.  Could there be a dialog box that pops up telling the end-user to select a token before setting a condition?

Please let me know if you need clarification...or if it is working as programmed. Thanks!

----

I've attached a screen shot... it was the bottom right Goblins turn, fyi.

![conditionset](https://user-images.githubusercontent.com/13898029/39964295-54282d4e-5636-11e8-938f-ab0c6355fa60.PNG)

![conditionset2](https://user-images.githubusercontent.com/13898029/39964329-e867a390-5636-11e8-9151-1a4ce2f992d2.PNG)

**Comment by RobinKuiper** [comment]
I will look into this one as soon as possible.

**Comment by RobinKuiper** [comment]
I can't seem to reproduce this, please try it again with the newest version. 

I will close this for now, let me know if you still get this.
