### ISSUE TITLE
[Lazy Experience] - Feature Request

### ISSUE THREAD

**Issue by teak421** [RobinKuiper/Roll20APIScripts#12]
Please consider adding some sort of notification inside the LazyExp Config screen that shows that a person is inactive.  Currently, you can click on config to get that information, but it would be quite handy to have it displayed right in that window.

Thanks for your great work...

![lazyexp](https://user-images.githubusercontent.com/13898029/39969666-1e9bfc60-5694-11e8-8132-1575f8f11d9d.PNG)

**Comment by RobinKuiper** [comment]
It should have a strikethrough when someone is set to inactive.

https://i.imgur.com/bqLJyRg.png

**Comment by teak421** [comment]
Hmmm... Mine doesn't show.  Here's Hogar (Jeff)'s config:

![image](https://user-images.githubusercontent.com/13898029/40022725-ab3604ce-577d-11e8-93a3-d107ac6fd69a.png)

Here's the output config screen: 

![image](https://user-images.githubusercontent.com/13898029/40022748-beba1dbe-577d-11e8-9236-7ec121a41352.png)

**Comment by teak421** [comment]
I'm on Chrome 66...

**Comment by RobinKuiper** [comment]
hm, strange, I will look into it.

**Comment by RobinKuiper** [comment]
Should be fixed in next update. I will close this for now.
