### ISSUE TITLE
API Console Crash

### ISSUE THREAD

**Issue by teak421** [RobinKuiper/Roll20APIScripts#13]
On one of my games I am getting the below error message when I attempt to start Combat Tracker.  Let me know if you need any additional information to help track this down.  I've re-loaded the script from scratch too...

![image](https://user-images.githubusercontent.com/13898029/39969890-6f4b3d9e-5697-11e8-8208-cf26315d3ddb.png)

**Comment by teak421** [comment]
It appears to be just that one specific game, the other games are working fine.  I was playing around with the LazyExp, I wonder if that did something here?

**Comment by teak421** [comment]
Well, now I got the below error in another game:

![image](https://user-images.githubusercontent.com/13898029/39970014-562e81a2-5699-11e8-91ef-8f30c477ff1e.png)

**Comment by RobinKuiper** [comment]
Should be fixed in the new update.
