### ISSUE TITLE
Combat Tracker: Feature Request - Option to whisper all turn announcements to the GM

### ISSUE THREAD

**Issue by keithcurtis1** [RobinKuiper/Roll20APIScripts#15]
I'd really not like to send every turn announcement to the players and fill up their chat. Is it possible to add a config to whisper turn announcements to GM?

**Comment by RobinKuiper** [comment]
I'm sorry, I was out of the running for some time, but I'm starting with Roll20 scripting again. I will add this option asap.

**Comment by RobinKuiper** [comment]
Next update (coming soon) will contain this. Will close this issue for now.
