### ISSUE TITLE
Skill proficiency missing

### ISSUE THREAD

**Issue by yorickdowne** [RobinKuiper/Roll20APIScripts#2]
Shaped 17.0.5, Import 0.0.4, json at https://pastebin.com/ynsz0VDk

Should have proficiency in Animal Handling, Athletics, Intimidation, Religion, Survival.

Animal Handling proficiency is missing.

**Comment by yorickdowne** [comment]
Ah, to elaborate: Skill is not marked as proficient, but this does show up in the text field "Proficiencies"

**Comment by RobinKuiper** [comment]
I have updated the script.
Skills proficiencies should all import correctly now.
