### ISSUE TITLE
[BeyondImporter] Flame Strike spell only imports one damage type

### ISSUE THREAD

**Issue by derammo** [RobinKuiper/Roll20APIScripts#20]
this spell does two types of damage, and only one is imported and attached to the attack

**Comment by RobinKuiper** [comment]
This should be fixed now in the development branch. Multi spell damage should import correctly.
I have tested this with a few characters/spells, but is should probably be tested some more.

**Comment by derammo** [comment]
just a heads up:   I compared the structure of Flame Strike (which applies two damage types) to the structure of Glyph of Warding (which allows you to CHOOSE among a bunch of damage types) and they are identical structurally, from what I can tell.  The only way you'd know not to apply all the damage types in Glyph of Warding is in the "restriction" field there is a message saying this, but it isn't structured info.   I plan to add the "restriction" to "description" of all attacks generated from spells anyway, so that you get clarifications like "Restriction: Whirlpool" when you click on Control Water (which only does damage if you choose the Whirlpool option) and also it will say something useful for other spells like what sort of target is immune

**Comment by derammo** [comment]
Bug: the spell "Life Transference" imports Necrotic damage and "Healing" with a "null" dice so it becomes a broken attack

**Comment by derammo** [comment]
released as 0.4.0 to master
