### ISSUE TITLE
[BeyondImporter] Attuned items not being added to AC

### ISSUE THREAD

**Issue by Andargor** [RobinKuiper/Roll20APIScripts#34]
Bracers of defense and Ring of Protection, in this case. For the latter, the bonus to saves is calculated.

**Comment by sillvva** [comment]
I just imported a character wearing some and the modifier was being applied correctly. Can you verify that your Bracers of Defense is showing `AC: +2` in the modifiers and that they are equipped?

**Comment by Andargor** [comment]
Yes, although I can't tell what is attuned on the 5e OGL sheet.

AC is 20 in D&D Beyond
https://i.imgur.com/nKd2zIL.png

AC is 17 in roll20
https://i.imgur.com/tv2rbD8.png

**Comment by sillvva** [comment]
Try this. Unequip one of those in Roll20 and see if your AC changes. If it does, then it was something else isn't working properly.

And yeah, a Roll20 Enhancement Suite export would be massively helpful. Either that or your D&D Beyond JSON in a pastebin.com entry would work.

**Comment by Andargor** [comment]
The character is public: https://www.dndbeyond.com/profile/Andargor/characters/820082

Can you see the JSON or do I need to pastebin?

**Comment by sillvva** [comment]
We can't access public character JSON unfortunately.

**Comment by Andargor** [comment]
Here's a Gist, pastebin too small: https://gist.github.com/Andargor/fc849eb85d69d343e37b3780efa876d8

And no, the Monk is another player :)

**Comment by sillvva** [comment]
Looks like a Draconic Resilience not being applied actually. Do you have an item in your Roll20 inventory that looks like "unarmored" something or other that is not equipped?

**Comment by Andargor** [comment]
Ah, yes I think that's it. I checked it equipped and the AC became 20. Can that be equipped automatically?

**Comment by sillvva** [comment]
It should have been. I can look into why it wasn't.

**Comment by sillvva** [comment]
Test with the character JSON above was successful. Inventory item is now correctly equipped and listed as Draconic Resilience, instead of Unarmed Defense.
