### ISSUE TITLE
[BeyondImporter] HP Discrepancy

### ISSUE THREAD

**Issue by Andargor** [RobinKuiper/Roll20APIScripts#35]
I have a Sorcerer 5/Warlock 2, Draconic Bloodline, 18 Con. in D&D Beyond, using fixed calculations, he has 65 HP. The import indicates 67 HP.

https://i.imgur.com/xzAQNnW.png

**Comment by sillvva** [comment]
67 is what you'd have using normal HP calculations. We can take a look at supporting fixed HP calculations too.

**Comment by Andargor** [comment]
So D&D beyond is wrong or are they applying a specific fixed calculation? That character's first level was Sorcerer, and not Warlock, which might account for the 2 HP discrepancy.

**Comment by sillvva** [comment]
Hmm, my math was wrong.

6 (1st Sorcerer level) + 4*4 (4 Sorcerer levels) + 2*5 (2 Warlock levels) + 7*4[CON] + 5 = 
6 + 16 + 10 + 28 + 5 = 65

Actually, it looks like it's applying draconic resilience to all 7 levels.

**Comment by sillvva** [comment]
Tested a character with the same build as above and the hit points imported were the correct number.
