### ISSUE TITLE
Subclass features missing

### ISSUE THREAD

**Issue by yorickdowne** [RobinKuiper/Roll20APIScripts#6]
Shaped 17.0.5, Import 0.0.4, json at https://pastebin.com/ynsz0VDk

Class Features for barb came in, but subclass features (Ancestral Guardian) are missing. There should be Primal Path, Ancestral Proctectors.

**Comment by yorickdowne** [comment]
Hmm. Yeah that's tricky. One way I can think of doing this is to use a "naive" approach, checking against the class features the script understands, and adding everything that's not in that list.

In case you decide to go that way, here's what the sheet can add directly:
Racial - Halfling Luck, Half-Orc Savage Attacks, Powerful Build (none automatic, need to be checked)
Artificer - Magic Item Analysis, Tool Expertise, Wondrous Invention, Infuse Magic, Superior Attunement, Mechanical Servant, Soul of Artifice
Barbarian - Rage, Unarmored Defense, Reckless Attack, Danger Sense, Fast Movement, Feral Instinct, Brutal Critical, Relentless Rage, Persistent Rage, Indomitable Might, Primal Champion
Bard - Bardic Inspiration, Jack of all Trades, Song of Rest, Expertise, Countercharm, Magical Secrets, Superior Inspiration
Cleric - Channel Divinity, Turn Undead (Channel Divinity), Divine Intervention
Druid - Druidic, Wild Shape, Timeless Body, Beast Spells, Archdruid
Fighter - Fighting Style (Fighter), Second Wind, Action Surge, Indomitable, Remarkable Athlete
Monk - Unarmored Defense, Martial Arts, Ki, Flurry of Blows, Patient Defense, Step of the Wind, Unarmored Movement, Deflect Missiles, Slow Fall, Stunning Strike, Ki-Empowered Strikes, Evasion, Stillness of Mind, Purity of Body, Tongue of the Sun and Moon, Diamond Soul, Timeless Body, Empty Body, Perfect Self
Paladin - Divine Sense, Lay on Hands, Fighting Style (Paladin), Divine Smite, Divine Health, Channel Divinity, Aura of Protection, Aura of Courage, Improved Divine Smite, Cleansing Touch
Ranger - Favored Enemy, Natural Explorer, Fighting Style (Ranger), Primeval Awareness, Land's Stride, Hide in Plain Sight, Vanish, Feral Senses, Foe Slayer
Ranger UA - Favored Enemy, Natural Explorer, Fighting Style (Ranger UA), Primeval Awareness, Greater Favored Enemy, Fleet of Foot, Hide in Plain Sight, Vanish, Feral Senses, Foe Slayer
Rogue - Expertise, Sneak Attack, Thieves' Cant, Cunning Action, Uncanny Dodge, Evasion, Reliable Talent, Blindsense, Slippery Mind, Elusive, Stroke of Luck
Sorcerer - Sorcery Points, Flexible Casting, Metamagic, Sorcerous Restoration, Careful Spell, Distant Spell, Empowered Spell, Extended Spell, Heightened Spell, Quickened Spell, Subtle Spell, Twinned Spell
Warlock - Eldritch Invocations, Pact Boon, Mystic Arcanum, Eldritch Master
Wizard - Arcane Recovery, Spell Mastery, Signature Spells

Some of these have subclass features and some do not. I think it's likely just "everything that's in the SRD".

**Comment by RobinKuiper** [comment]
Wow, thanks for the list man! I will look in to this indeed.
